### PR TITLE
Register new threads with the collector

### PR DESCRIPTION
**Pull request by jacob-hughes**

### CODE REVIEW

**Comment by ltratt** [comment]
Can we add a multi-threaded test to the test suite to verify that this works (and stays working)?

**Comment by jacob-hughes** [comment]
So that's what `src/test/ui/threads-sendsync/thread_registration.rs` is supposed to do. It spawns a new thread and then queries the collector to see if it's been registered as a rootset.

**Comment by ltratt** [comment]
Shouldn't we have a test which does some malloc'ing and freeing to check it doesn't bork? I assume that, before this PR, such code would actively fail?

**Comment by jacob-hughes** [comment]
Yeah that would be ideal, but it's not possible to do this in rustc though because the actual `Gc<T>` implementations are in `libgc`, and pulling libgc into the `ui` test suite is causing me a real headache. I'm now writing such tests as part of the `libgc` Send + Sync PR. Is that ok?

**Comment by ltratt** [comment]
> I'm now writing such tests as part of the libgc Send + Sync PR.

OK, that's fine. I'll merge this in advance, because that'll hopefully make your life a bit easier.

bors r+

**Comment by jacob-hughes** [comment]
Thanks!

**Comment by jacob-hughes** [comment]
This is a [bug in libgc](https://github.com/softdevteam/libgc/pull/55). I remember fixing this locally but left the fix in my working tree for some reason :facepalm:. Once that merges, this will be unblocked.

**Comment by jacob-hughes** [comment]
Ah! That's an interesting one. This is failing on rustc's gdb tests, they work by: compiling something; prodding around in gdb; and then diffing gdb's output. I permanently disabled this locally because arch-linux packages a subtly different gdb version which formats things differently in stdout. That's why this would have been missed by bors.

The actual issue here is pretty straightforward: in the `GcAllocator::init` call, Boehm temporarily replaces the SIGSEGV handler to work out the start / end range of the data segment. Since gdb doesn't know about this, you have to manually `continue` to recover from the signal. Let me see if there's a way to do this automatically in the test suite.

**Comment by ltratt** [comment]
Ouch -- OK!

**Comment by jacob-hughes** [comment]
This is ready for merging again.

**Pull request merged**
