### PR TITLE
Add set_managed ffi 

### PR DESCRIPTION
**Pull request by jacob-hughes**
This introduces various changes necessary for the make_collectable intrinsic to work. See each commit message for details.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Unfortunately we have to revert 187b32f6c7236db8fa301039a06831bd2376f029. When Boehm OOMs it behaves slightly differently to system malloc. This means that we get test failures in rustc which will be hard to maintain because of subtle differences in stderr and status codes.

**Comment by ltratt** [comment]
What does this mean for the "set managed" stuff? I vaguely assumed that implied that all memory must be allocated with Boehm?

**Comment by jacob-hughes** [comment]
It does. It means that we have to require that user programs switch their global allocator to `GcAllocator` as before.

**Comment by ltratt** [comment]
Ah, I see!

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
