### PR TITLE
Prevent early finalization

### PR DESCRIPTION
**Pull request by jacob-hughes**
This is a draft PR because I'm still debugging the test suite.

Currently `Gc` is defined in the libgc crate. The compiler isn't aware
of this so can't perform any specific operations on the `Gc` type. To
fix this, we introduce a `GcSmartPointer` trait which `libgc::Gc` will
implement.

This should be temporary. Eventually, the `Gc` smart pointer will be
part of the standard library. Right now though, it's convenient for
development that they are separated.

### CODE REVIEW

**Comment by ltratt** [comment]
I don't see any problem with what's here so far, other than that we will certainly need to add tests to the test suite to make sure that our pass is doing what we think it should do. I suggest that we'll want a fairly large number of test cases, though they'll mostly be variations on a theme, so shouldn't be *too* difficult to generate.

**Comment by jacob-hughes** [comment]
Yep. I've got a fair few done now, and they've mostly teased out invariants in the MIR I missed which I was not aware of. There is a really nasty inlining bug which I'm trying to fix, but once that's done I'll re-push and make this mergeable

**Comment by jacob-hughes** [comment]
Finally fix the bug where barriers weren't inserted if functions were inlined :tada: Here's some tests and a fix. I've marked this PR as merge-able now (but it will need squashing)

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Comment by ltratt** [comment]
@jacob-hughes Where are we with this?

**Comment by jacob-hughes** [comment]
This pass works by extracting MIR from the DefID of a `keep_alive` function in libcore. It can't seem to find the MIR when building later stages of the compiler so I'm hand building the MIR instead.

**Comment by ltratt** [comment]
Does that mean we can try bors'ing again or ... ?

**Comment by jacob-hughes** [comment]
I'll push a fix shortly

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
This is ready for re-review now.

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
