### PR TITLE
Replace `NoFinalize + OnlyFinalizeComponents` with single `FinalizerOptional` trait

### PR DESCRIPTION
**Pull request by jacob-hughes**
The individual commit message explains how this change works, but in summary, this removes a lot of the nasty edge cases that made finaliser elision really tricky to use.

I've had to temporarily disable the early finalisation pass for this to build. It has teased out a problem in it where we can sometimes infinitely recurse when checking the trait bounds. The next PR fixes this, but wanted to separate them as it was getting too big.

### CODE REVIEW

**Comment by ltratt** [comment]
`FinalizerOptional` -- excellent name!

**Comment by jacob-hughes** [comment]
bors try

**Comment by ltratt** [comment]
If the `try` succeeds, please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
