### PR TITLE
Upstream sync

### PR DESCRIPTION
**Pull request by jacob-hughes**
Temporarily removed `needs_finalizer` implementation because changes to rustc broke it. This will be fixed in an upcoming PR.

### CODE REVIEW

**Comment by vext01** [comment]
```
‘python’: No such file or directory
```

You can use `python2` or `python3` (or more specific versions).

**Comment by jacob-hughes** [comment]
I've updated this so that `.buildbot.sh` uses `python3` explicilty. Can you try again @ltratt ?

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors cancel

**Comment by jacob-hughes** [comment]
bors try-

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors ping

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try-

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
Hmm. It seems like buildbot doesn't want to run anymore?

**Comment by ltratt** [comment]
I can see something running -- I think you need to give it a bit. For some reason the orange dot doesn't always appear in github (whether that's github or buildbot I don't know).

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
bors try

**Pull request merged**
